---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "/opt/Training/python/automation_training/nornir/hosts.yaml"
        group_file: "/opt/Training/python/automation_training/nornir/groups.yaml"
        defaults_file: "/opt/Training/python/automation_training/nornir/defaults.yaml"


runner:
    plugin: threaded
    options:
        num_workers: 10