---

inventory:
    plugin: SimpleInventory
    options:
        host_file: "/mnt/googledrive/Training/Training/python/cbt_network_automation_python/nornir/hosts.yaml"
        group_file: "/mnt/googledrive/Training/Training/python/cbt_network_automation_python/nornir/groups.yaml"
        defaults_file: "/mnt/googledrive/Training/Training/python/cbt_network_automation_python/nornir/defaults.yaml"


runner:
    plugin: threaded
    options:
        num_workers: 10